using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Moolah")]
[assembly: AssemblyDescriptionAttribute("Easy payment processing for .NET (DataCash, PayPal)")]
[assembly: AssemblyCopyrightAttribute("Copyright David Duffett 2014")]
[assembly: AssemblyVersionAttribute("0.7.4")]
[assembly: AssemblyFileVersionAttribute("0.7.4")]
[assembly: AssemblyInformationalVersionAttribute("0.7.4")]

